### ISSUE TITLE
Cannot running in VS2019

### ISSUE THREAD

**Issue by Catfoxcat** [codetronik/DepthFantasiaHack#1]
I imported this project into vs2019 and set the platform toolset to Intel C++ Compiler 19.1.
There are some errors after running this code.

error : Opcode PUSHAD unsupported by architecture in asm instruction pushad.
error : Opcode PUSHFD unsupported by architecture in asm instruction pushfd.
error : Opcode POPFD unsupported by architecture in asm instruction popfd.
error : Opcode POPAD unsupported by architecture in asm instruction popad.

may I know how to fix it? (or can you release the .exe file?) thanks.

**Comment by codetronik** [comment]
Does it occur in 32-bit release mode? Also you can download release file this link. https://github.com/codetronik/DepthFantasiaHack/releases/tag/1

**Comment by Catfoxcat** [comment]
It occurs in 64-bit mode. I tried to use 32-bit mode but it has other errors.
I feel sorry that can you tell me how to use this .dll file?
I put it to the game path and run the game but it does not work. Thanks.
